Cherry-pick 292680@main (120eef401f7c). https://bugs.webkit.org/show_bug.cgi?id=290259
    ResourceLoadInfo: fix compilation if VIDEO or is not enabled

    https://bugs.webkit.org/show_bug.cgi?id=290259

    Reviewed by Adrian Perez de Castro.

    /home/thomas/br-test-pkg/bootlin-armv7-glibc/build/webkitgtk-2.48.0/Source/WebCore/loader/ResourceLoadInfo.cpp:88:32: error: ‘TextTrackResource’ is not a member of ‘WebCore::CachedResource::Type’
       88 |     case CachedResource::Type::TextTrackResource:
          |                                ^~~~~~~~~~~~~~~~~

    Commit https://github.com/WebKit/WebKit/commit/951a118e17cd92adc3aa31129af7cd348fac91e9
    "Fix missing includes and guards when certain features are disabled",
    added guards to TextTrackResource in CachedResource, but forgot to
    add this one.

    Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>
    Canonical link: https://commits.webkit.org/292680@main

Canonical link: https://commits.webkit.org/290945.100@webkitglib/2.48