Cherry-pick 291283@main (757540b9d783). https://bugs.webkit.org/show_bug.cgi?id=285806
    [Glib] Fix build on non-Linux platforms
    https://bugs.webkit.org/show_bug.cgi?id=285806

    Reviewed by Michael Catanzaro

    2d331cef5d1c ("Address static analysis warnings related to RunLoop")
    updated the non-Linux code, but missed adding "mutable" there like it
    did for the common part, leading to the following error:

    In file included from /build/webkit2gtk-2.47.4/build-soup3/WTF/Headers/wtf/FastMalloc.h:26,
                     from /build/webkit2gtk-2.47.4/build-soup3/WTF/Headers/wtf/TZoneMalloc.h:35,
                     from /build/webkit2gtk-2.47.4/Source/WebKit/WebKit2Prefix.h:67,
                     from <command-line>:
    /build/webkit2gtk-2.47.4/Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp: In lambda function:
    /build/webkit2gtk-2.47.4/build-soup3/WTF/Headers/wtf/StdLibExtras.h:1502:58: error: binding reference of type ‘WTF::UnixFileDescriptor&&’ to ‘std::remove_reference<const WTF::UnixFileDescriptor&>::type’ {aka ‘const WTF::UnixFileDescriptor’} discards qualifiers
     1502 | #define WTFMove(value) std::move<WTF::CheckMoveParameter>(value)
          |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
    /build/webkit2gtk-2.47.4/Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp:278:78: note: in expansion of macro ‘WTFMove’
      278 |         didFinishLaunchingProcess(m_processID, IPC::Connection::Identifier { WTFMove(serverSocket) });
          |                                                                              ^~~~~~~
    In file included from /build/webkit2gtk-2.47.4/Source/WebKit/UIProcess/Launcher/ProcessLauncher.h:28,
                     from /build/webkit2gtk-2.47.4/Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp:28:
    /build/webkit2gtk-2.47.4/Source/WebKit/Platform/IPC/Connection.h:273:50: note:   initializing argument 1 of ‘IPC::Connection::Identifier::Identifier(WTF::UnixFileDescriptor&&)’
      273 |         explicit Identifier(UnixFileDescriptor&& fd)
          |                             ~~~~~~~~~~~~~~~~~~~~~^~
    /build/webkit2gtk-2.47.4/build-soup3/WTF/Headers/wtf/StdLibExtras.h: In instantiation of ‘constexpr typename std::remove_reference<_Arg>::type&& std::move(T&&) [with WTF::CheckMoveParameterTag <anonymous> = WTF::CheckMoveParameter; T = const WTF::UnixFileDescriptor&; typename remove_reference<_Arg>::type = const WTF::UnixFileDescriptor]’:
    /build/webkit2gtk-2.47.4/Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp:278:78:   required from here
     1502 | #define WTFMove(value) std::move<WTF::CheckMoveParameter>(value)
          |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
    /build/webkit2gtk-2.47.4/build-soup3/WTF/Headers/wtf/StdLibExtras.h:923:51: error: static assertion failed: T is const qualified.
      923 |     static_assert(!is_const<NonRefQualifiedType>::value, "T is const qualified.");
          |                                                   ^~~~~
    /build/webkit2gtk-2.47.4/build-soup3/WTF/Headers/wtf/StdLibExtras.h:923:51: note: ‘!(bool)std::integral_constant<bool, true>::value’ evaluates to false
    ninja: build stopped: subcommand failed.

    * Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp:
    (WebKit::ProcessLauncher::launchProcess):

    Canonical link: https://commits.webkit.org/291283@main

Canonical link: https://commits.webkit.org/290945.5@webkitglib/2.48